

import type { Metadata } from "next";
import { Akatab } from "next/font/google";
// import 'bootstrap/dist/css/bootstrap.min.css'
import '@fortawesome/fontawesome-free/css/all.min.css'
import "./globals.css"

import Navbar from "./Navbar/navbar";
import Footer from "./Footer/Footer";
import { ThemeProvider } from "./theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Akatab ({ subsets: ["latin"],weight:"600" });

export const metadata: Metadata = {
  title: "Movie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider >

        <html lang="en">
              


        <body className={inter.className}>
        <ThemeProvider attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange>
          
        <Navbar/>
       {children}
        <Footer/>
       
        </ThemeProvider>
        

        
        
        </body>


      
    </html>
    </ClerkProvider>
  
    
  );
}
